# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMembers',
            new_name='ProjectMember',
        ),
    ]
