# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_completed',
            new_name='date',
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
