# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='gsoc',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='intern',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ('-date',)},
        ),
    ]
