# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20170619_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='area',
        ),
    ]
