# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_article_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='year',
        ),
        migrations.AddField(
            model_name='contribution',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
