# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_auto_20170618_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='org_name',
            new_name='organisation',
        ),
        migrations.AddField(
            model_name='contribution',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(null=True),
        ),
    ]
