# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_auto_20170618_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
