# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='date',
            field=models.DateField(),
        ),
    ]
