# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20170913_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniinfo',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='alumniinfo',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumniinfo',
            name='resume',
            field=models.FileField(default='null', upload_to='resume/'),
        ),
    ]
