# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusreport',
            name='project',
        ),
        migrations.RemoveField(
            model_name='statusreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='StatusReport',
        ),
    ]
