# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='title',
            field=models.CharField(max_length=300, null='True'),
        ),
    ]
