# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubManagement', '0002_auto_20180311_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
    ]
