# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubManagement', '0004_auto_20170615_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResponsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='responsibility',
            old_name='responsibility',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='user',
        ),
        migrations.AddField(
            model_name='responsibility',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentresponsibility',
            name='responsibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubManagement.Responsibility'),
        ),
        migrations.AddField(
            model_name='studentresponsibility',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
