# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubManagement', '0005_auto_20170615_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='TeamMember',
        ),
    ]
