# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contest/poster/'),
        ),
    ]
