# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='startdate',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
