# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeBoard', '0002_auto_20170924_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
