# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_userinfo_is_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
