# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_userinfo_small_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='googlePlus',
            new_name='email',
        ),
    ]
