# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20171218_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature_pics/'),
        ),
    ]
