# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_userinfo_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_freelance',
            field=models.BooleanField(default=False),
        ),
    ]
