# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_userinfo_is_freelance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
