# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_userinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='work_description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
