# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20171218_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('work_description', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='work_description',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='workExp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.UserInfo'),
        ),
    ]
