# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-23 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20171219_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='codeforces',
            field=models.URLField(blank=True),
        ),
    ]
