# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinapplication',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
