# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinapplication',
            name='roll_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
