# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_joinapplication_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinapplication',
            name='batch',
            field=models.CharField(choices=[('1st year', '1st year'), ('2nd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year')], max_length=100),
        ),
    ]
