# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_joinapplication_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinapplication',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
