# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-21 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20170913_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinapplication',
            name='contribution',
            field=models.TextField(default='NULL'),
        ),
    ]
