# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogFeedAggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
