# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogFeedAggregator', '0003_article_imagehref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='imageHref',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
