# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='workshop/poster/'),
        ),
        migrations.AlterField(
            model_name='workshopgallery',
            name='image',
            field=models.ImageField(upload_to='workshop/images/'),
        ),
    ]
