# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
