# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopfeedback',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
