# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistration',
            name='course',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='hostel_details',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='section',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
