# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopgallery',
            name='date',
        ),
        migrations.AddField(
            model_name='workshop',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
