# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20170918_1508'),
        ('workshop', '0002_auto_20170921_0057'),
    ]

    operations = [
    ]
