# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_workshop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='other_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='course_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='project',
            field=models.TextField(blank=True),
        ),
    ]
