# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20180207_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='number_of_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
