# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20170914_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workshop/images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='workshop',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='male_or_female',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='workshopgallery',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Workshop'),
        ),
    ]
