# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-17 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_workshopfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopfeedback',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.Workshop'),
        ),
    ]
