# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-04 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyAttendance',
        ),
        migrations.DeleteModel(
            name='YearlyAttendance',
        ),
    ]
